ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "placedByUserId" TEXT;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "placedByName" TEXT;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "paidByUserId" TEXT;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "paidByName" TEXT;

ALTER TABLE "OrderItem" ADD COLUMN IF NOT EXISTS "preparedByUserId" TEXT;
ALTER TABLE "OrderItem" ADD COLUMN IF NOT EXISTS "preparedByName" TEXT;
ALTER TABLE "OrderItem" ADD COLUMN IF NOT EXISTS "readyByUserId" TEXT;
ALTER TABLE "OrderItem" ADD COLUMN IF NOT EXISTS "readyByName" TEXT;
ALTER TABLE "OrderItem" ADD COLUMN IF NOT EXISTS "servedByUserId" TEXT;
ALTER TABLE "OrderItem" ADD COLUMN IF NOT EXISTS "servedByName" TEXT;
