ALTER TABLE "Restaurant" ADD COLUMN IF NOT EXISTS "receiptAddress" TEXT;
ALTER TABLE "Restaurant" ADD COLUMN IF NOT EXISTS "receiptPhone" TEXT;
ALTER TABLE "Restaurant" ADD COLUMN IF NOT EXISTS "receiptGstin" TEXT;
ALTER TABLE "Restaurant" ADD COLUMN IF NOT EXISTS "receiptGstEnabled" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Restaurant" ADD COLUMN IF NOT EXISTS "receiptGstRate" DOUBLE PRECISION NOT NULL DEFAULT 5;
ALTER TABLE "Restaurant" ADD COLUMN IF NOT EXISTS "receiptFooter" TEXT;
