export const AUDIT_EVENT_KIND = {
  REQUEST: "REQUEST",
  ACTION: "ACTION",
  SECURITY: "SECURITY",
  ERROR: "ERROR",
} as const;

export const AUDIT_SEVERITY = {
  INFO: "INFO",
  WARN: "WARN",
  ERROR: "ERROR",
  CRITICAL: "CRITICAL",
} as const;

export const AUDIT_OUTCOME = {
  SUCCESS: "SUCCESS",
  DENIED: "DENIED",
  FAILED: "FAILED",
} as const;

export const AUDIT_SOURCE = {
  API: "API",
  PAGE: "PAGE",
  WEBHOOK: "WEBHOOK",
  AGENT: "AGENT",
  WORKER: "WORKER",
  SYSTEM: "SYSTEM",
} as const;

export const AUDIT_CATEGORY = {
  AUTH: "AUTH",
  PLATFORM: "PLATFORM",
  STAFF: "STAFF",
  MENU: "MENU",
  ORDER: "ORDER",
  MONEY: "MONEY",
  PRINTING: "PRINTING",
  CONFIG: "CONFIG",
  SECURITY: "SECURITY",
  SYSTEM: "SYSTEM",
  INTEGRATION: "INTEGRATION",
} as const;

export const AUDIT_ACTOR_TYPE = {
  PLATFORM_ADMIN: "PLATFORM_ADMIN",
  TENANT_ADMIN: "TENANT_ADMIN",
  STAFF: "STAFF",
  CUSTOMER: "CUSTOMER",
  PRINTER_AGENT: "PRINTER_AGENT",
  PAYMENT_PROVIDER: "PAYMENT_PROVIDER",
  SYSTEM: "SYSTEM",
  ANONYMOUS: "ANONYMOUS",
} as const;

export const AUDIT_ACTION = {
  API_REQUEST: "API_REQUEST",
  REQUEST_FAILED: "REQUEST_FAILED",

  STAFF_LOGIN_SUCCEEDED: "STAFF_LOGIN_SUCCEEDED",
  STAFF_LOGIN_FAILED: "STAFF_LOGIN_FAILED",
  STAFF_LOGOUT: "STAFF_LOGOUT",
  TENANT_ADMIN_LOGIN_SUCCEEDED: "TENANT_ADMIN_LOGIN_SUCCEEDED",
  TENANT_ADMIN_LOGIN_FAILED: "TENANT_ADMIN_LOGIN_FAILED",
  TENANT_ADMIN_LOGOUT: "TENANT_ADMIN_LOGOUT",
  PLATFORM_ADMIN_LOGIN_SUCCEEDED: "PLATFORM_ADMIN_LOGIN_SUCCEEDED",
  PLATFORM_ADMIN_LOGIN_FAILED: "PLATFORM_ADMIN_LOGIN_FAILED",
  PLATFORM_ADMIN_LOGOUT: "PLATFORM_ADMIN_LOGOUT",
  SESSION_REJECTED: "SESSION_REJECTED",
  AUTHENTICATION_FAILED: "AUTHENTICATION_FAILED",
  PERMISSION_DENIED: "PERMISSION_DENIED",

  WRONG_HOST_ACCESS_DENIED: "WRONG_HOST_ACCESS_DENIED",
  CROSS_RESTAURANT_ACCESS_DENIED: "CROSS_RESTAURANT_ACCESS_DENIED",
  CROSS_TENANT_ACCESS_DENIED: "CROSS_TENANT_ACCESS_DENIED",
  ROLE_PERMISSION_DENIED: "ROLE_PERMISSION_DENIED",
  INVALID_PRINTER_AGENT_TOKEN: "INVALID_PRINTER_AGENT_TOKEN",
  REVOKED_PRINTER_AGENT_TOKEN: "REVOKED_PRINTER_AGENT_TOKEN",
  RAZORPAY_SIGNATURE_INVALID: "RAZORPAY_SIGNATURE_INVALID",
  PUBLIC_TOKEN_HOST_MISMATCH: "PUBLIC_TOKEN_HOST_MISMATCH",
  PLATFORM_AUDIT_ACCESS_DENIED: "PLATFORM_AUDIT_ACCESS_DENIED",
  AUDIT_TAMPER_ATTEMPT: "AUDIT_TAMPER_ATTEMPT",

  STAFF_CREATED: "STAFF_CREATED",
  STAFF_UPDATED: "STAFF_UPDATED",
  STAFF_ROLE_CHANGED: "STAFF_ROLE_CHANGED",
  STAFF_ENABLED: "STAFF_ENABLED",
  STAFF_DISABLED: "STAFF_DISABLED",
  STAFF_DELETED: "STAFF_DELETED",

  MENU_CATEGORY_CREATED: "MENU_CATEGORY_CREATED",
  MENU_CATEGORY_UPDATED: "MENU_CATEGORY_UPDATED",
  MENU_CATEGORY_DELETED: "MENU_CATEGORY_DELETED",
  MENU_ITEM_CREATED: "MENU_ITEM_CREATED",
  MENU_ITEM_UPDATED: "MENU_ITEM_UPDATED",
  MENU_ITEM_DELETED: "MENU_ITEM_DELETED",
  MENU_ITEM_PRICE_CHANGED: "MENU_ITEM_PRICE_CHANGED",
  MENU_ITEM_AVAILABILITY_CHANGED: "MENU_ITEM_AVAILABILITY_CHANGED",
  MENU_ITEM_IMAGE_UPLOADED: "MENU_ITEM_IMAGE_UPLOADED",
  MENU_ITEM_IMAGE_REPLACED: "MENU_ITEM_IMAGE_REPLACED",
  MENU_ITEM_IMAGE_REMOVED: "MENU_ITEM_IMAGE_REMOVED",

  ORDER_CREATED: "ORDER_CREATED",
  ORDER_ITEM_ADDED: "ORDER_ITEM_ADDED",
  ORDER_ITEM_UPDATED: "ORDER_ITEM_UPDATED",
  ORDER_ITEM_REMOVED: "ORDER_ITEM_REMOVED",
  ORDER_STATUS_CHANGED: "ORDER_STATUS_CHANGED",
  ORDER_CANCELLED: "ORDER_CANCELLED",
  TABLE_SWITCHED: "TABLE_SWITCHED",
  DISCOUNT_CHANGED: "DISCOUNT_CHANGED",
  PROMO_APPLIED: "PROMO_APPLIED",
  PROMO_REMOVED: "PROMO_REMOVED",

  BILL_FINALIZED: "BILL_FINALIZED",
  PAYMENT_RECORDED: "PAYMENT_RECORDED",
  CASH_PAYMENT_CAPTURED: "CASH_PAYMENT_CAPTURED",
  MANUAL_UPI_SUBMITTED: "MANUAL_UPI_SUBMITTED",
  MANUAL_UPI_VERIFIED: "MANUAL_UPI_VERIFIED",
  MANUAL_UPI_REJECTED: "MANUAL_UPI_REJECTED",
  GATEWAY_ATTEMPT_CREATED: "GATEWAY_ATTEMPT_CREATED",
  RAZORPAY_ORDER_CREATED: "RAZORPAY_ORDER_CREATED",
  RAZORPAY_ORDER_RECOVERED: "RAZORPAY_ORDER_RECOVERED",
  RAZORPAY_CALLBACK_VERIFIED: "RAZORPAY_CALLBACK_VERIFIED",
  RAZORPAY_CALLBACK_REJECTED: "RAZORPAY_CALLBACK_REJECTED",
  RAZORPAY_WEBHOOK_RECEIVED: "RAZORPAY_WEBHOOK_RECEIVED",
  RAZORPAY_WEBHOOK_ACCEPTED: "RAZORPAY_WEBHOOK_ACCEPTED",
  RAZORPAY_WEBHOOK_REPLAYED: "RAZORPAY_WEBHOOK_REPLAYED",
  RAZORPAY_WEBHOOK_REJECTED: "RAZORPAY_WEBHOOK_REJECTED",
  PAYMENT_CAPTURED: "PAYMENT_CAPTURED",
  PAYMENT_CAPTURE_REPLAYED: "PAYMENT_CAPTURE_REPLAYED",
  REFUND_REQUESTED: "REFUND_REQUESTED",
  REFUND_REPLAYED: "REFUND_REPLAYED",
  REFUND_PROVIDER_PENDING: "REFUND_PROVIDER_PENDING",
  REFUND_COMPLETED: "REFUND_COMPLETED",
  REFUND_FAILED: "REFUND_FAILED",
  PAYMENT_RECONCILED: "PAYMENT_RECONCILED",

  GATEWAY_PROVIDER_CHANGED: "GATEWAY_PROVIDER_CHANGED",
  GATEWAY_CONFIGURATION_CHANGED: "GATEWAY_CONFIGURATION_CHANGED",
  GATEWAY_CREDENTIAL_ROTATED: "GATEWAY_CREDENTIAL_ROTATED",
  GATEWAY_WEBHOOK_SECRET_ROTATED: "GATEWAY_WEBHOOK_SECRET_ROTATED",
  GATEWAY_CREDENTIAL_CHANGE_DENIED: "GATEWAY_CREDENTIAL_CHANGE_DENIED",
  AUTOMATIC_UPI_SETTING_CHANGED: "AUTOMATIC_UPI_SETTING_CHANGED",

  PRINT_JOB_QUEUED: "PRINT_JOB_QUEUED",
  PRINT_JOB_CLAIMED: "PRINT_JOB_CLAIMED",
  PRINT_JOB_ACKED: "PRINT_JOB_ACKED",
  PRINT_JOB_ACK_REPLAYED: "PRINT_JOB_ACK_REPLAYED",
  PRINT_JOB_FAILED: "PRINT_JOB_FAILED",
  PRINT_JOB_RETRY_SCHEDULED: "PRINT_JOB_RETRY_SCHEDULED",
  PRINT_JOB_MANUAL_RETRY: "PRINT_JOB_MANUAL_RETRY",
  PRINT_JOB_REPRINTED: "PRINT_JOB_REPRINTED",
  PRINT_JOB_AMBIGUOUS: "PRINT_JOB_AMBIGUOUS",
  PRINTER_AGENT_CREATED: "PRINTER_AGENT_CREATED",
  PRINTER_AGENT_UPDATED: "PRINTER_AGENT_UPDATED",
  PRINTER_AGENT_TOKEN_ROTATED: "PRINTER_AGENT_TOKEN_ROTATED",
  PRINTER_AGENT_REVOKED: "PRINTER_AGENT_REVOKED",
  PRINTER_AGENT_AUTH_FAILED: "PRINTER_AGENT_AUTH_FAILED",

  RESTAURANT_SETTINGS_CHANGED: "RESTAURANT_SETTINGS_CHANGED",
  GST_SETTING_CHANGED: "GST_SETTING_CHANGED",
  RECEIPT_SETTINGS_CHANGED: "RECEIPT_SETTINGS_CHANGED",
  TENANT_ENABLED: "TENANT_ENABLED",
  TENANT_DISABLED: "TENANT_DISABLED",
  RESTAURANT_ENABLED: "RESTAURANT_ENABLED",
  RESTAURANT_DISABLED: "RESTAURANT_DISABLED",
  TENANT_CREATED: "TENANT_CREATED",
  RESTAURANT_CREATED: "RESTAURANT_CREATED",

  PAYMENT_VIEWED: "PAYMENT_VIEWED",
  CUSTOMER_DETAILS_VIEWED: "CUSTOMER_DETAILS_VIEWED",
  GATEWAY_CONFIG_VIEWED: "GATEWAY_CONFIG_VIEWED",
  AUDIT_VIEWED: "AUDIT_VIEWED",
  PUBLIC_RECEIPT_ACCESSED: "PUBLIC_RECEIPT_ACCESSED",

  BACKGROUND_JOB_FAILED: "BACKGROUND_JOB_FAILED",
  BACKGROUND_JOB_RETRY: "BACKGROUND_JOB_RETRY",
  PAYMENT_PROVIDER_API_FAILED: "PAYMENT_PROVIDER_API_FAILED",
  RAZORPAY_REFUND_API_FAILED: "RAZORPAY_REFUND_API_FAILED",
  WEBHOOK_PROCESSING_FAILED: "WEBHOOK_PROCESSING_FAILED",
  PRINT_DELIVERY_FAILED: "PRINT_DELIVERY_FAILED",
  DATABASE_OPERATION_FAILED: "DATABASE_OPERATION_FAILED",
  FORENSIC_AUDIT_WRITE_FAILED: "FORENSIC_AUDIT_WRITE_FAILED",
} as const;

export type AuditAction = (typeof AUDIT_ACTION)[keyof typeof AUDIT_ACTION];
export type AuditCategory = (typeof AUDIT_CATEGORY)[keyof typeof AUDIT_CATEGORY];
export type AuditActorType = (typeof AUDIT_ACTOR_TYPE)[keyof typeof AUDIT_ACTOR_TYPE];

export const FORENSIC_LIMITS = {
  userAgent: 1024,
  errorMessage: 2048,
  jsonField: 16 * 1024,
  forwardedFor: 512,
  actorName: 200,
  resourceLabel: 200,
  route: 300,
  hostname: 253,
  stack: 8 * 1024,
} as const;

export const SQLITE_APPEND_ONLY_TRIGGERS = `
CREATE TRIGGER IF NOT EXISTS "platform_audit_event_no_update"
BEFORE UPDATE ON "PlatformAuditEvent"
BEGIN
    SELECT RAISE(ABORT, 'PlatformAuditEvent is append-only');
END;
CREATE TRIGGER IF NOT EXISTS "platform_audit_event_no_delete"
BEFORE DELETE ON "PlatformAuditEvent"
BEGIN
    SELECT RAISE(ABORT, 'PlatformAuditEvent is append-only');
END;
`;
